### ISSUE TITLE
Login nicht möglich

### ISSUE THREAD

**Issue by thedespo** [PanCakeConnaisseur/user_backend_sql_raw#1]
Hallo, wie per eMail angefordert hier nun meine Meldung:

Login ist mit einem User einer Datenbank von Woltlab nicht möglich. Frontend Fehler: Falsches Passwort. 

Meine Queries:
		'get_password_hash_for_user' => 'SELECT * FROM wcf1_user WHERE password = :username',
		'user_exists' => 'SELECT EXISTS(SELECT * FROM wcf1_user WHERE username = :username)',
		'get_users' => 'SELECT * FROM wcf1_user WHERE (username ILIKE :search) OR (display_name ILIKE :search)',

Datenbankinfos:
DB: **mariadb**
DB Name: **woltlab_**
Tabellenname: **wcf1_user**
Spalten: **username** und **password**

Hier noch ein Auszug der Datenbank:
[2018-06-21 20_38_03-window](https://user-images.githubusercontent.com/15637078/41738820-6529f74a-7593-11e8-91fc-06a8f06f7943.png)

Beispiel Hash:
$2a$08$6WngfC2Fo9LBwus1NxiisOExnI3nNj3GimcwNQeArSPKvH2SFMntS
$2y$10$GGBCqsrmycqYy9wxfsJ2Z.4L7tdmkaEvsXEdolQdGHLO3mZqOPrH.

[nextcloud.log](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/files/2124894/nextcloud.log)
(Zum Datenschutz wurde meine IP sowie die Domain abgeändert, sonst ist alles Original)

Ich hoffe ich habe nichts vergessen, falls doch einfach melden.

Wäre schön wenn Sie mich hier unterstützen können.

Viele Grüße
the.despo - Patrick

**Comment by PanCakeConnaisseur** [comment]
Der Log enthält afaics nichts sinnvolles. Ich glaube, du hast ein Problem mit dem Log selbst. Was ich aber so schon sehe, ist dass du MariaDb nutzt und dieses kein `ILIKE` unterstützt. Die `get_users` query kann also nicht funktionieren. Die case insensitive Suche bei MariaDB benötigt afaics deutlich kompliziertere Queries (ein Grund wieso ich PostgreSQL favorisiere).

Du solltest also zunächst deine Logfileerstellung korrekt einstellen und die Queries anpassen.

Außerdem, wenn möglich bitte auf Englisch kommunizieren, damit mehr Nutzer, bei ähnlichen Problemen, etwas davon haben.
