### ISSUE TITLE
user admin issue after upgrade from NC13->NC14

### ISSUE THREAD

**Issue by digitalkram** [PanCakeConnaisseur/user_backend_sql_raw#11]
hi there

after upgrade when managing users in the backend there is an error message and this appears in the logs:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''50' OFFSET '0''
```

As you can see the prepared statment has quoted values for LIMIT and OFFSET integer paramaters in the end

=> not working

(see also https://stackoverflow.com/questions/10014147/limit-keyword-on-mysql-with-prepared-statement)

dirty quick "fix" in UserBackend.php:
```
                } else {
                        $limitSegment = ' LIMIT '.$limit;
                        //$parameterSubstitutions['limit'] = $limit;
                }

                if (is_null($offset)) {
                        $offsetSegment = '';
                } else {
                        $offsetSegment = ' OFFSET '.$offset;
                        //$parameterSubstitutions['offset'] = $offset;
                }
```

But that is surely just a hack. Sadly I lack the PHP knowledge to come up with the correct solution.

Cheers

**Comment by PanCakeConnaisseur** [comment]
Probably a duplicate of #4

**Comment by digitalkram** [comment]
Definitely a duplicate. Closing it now. Funny thing is that I commented on #4 a while ago that the PR linked there fixes the problem for me. I just forgot and during next installation after NC update I opened up this issue... Oops.

**Comment by digitalkram** [comment]
Definitely a duplicate. Closing it now. Funny thing is that I commented on #4 a while ago that the PR linked there fixes the problem for me. I just forgot and during next installation after NC update I opened up this issue... Oops.
