### ISSUE TITLE
mysql over ssl connection

### ISSUE THREAD

**Issue by johnwmail** [PanCakeConnaisseur/user_backend_sql_raw#13]
Hi, Is it possible, config mysql connection over ssl support?
Thanks.

**Comment by PanCakeConnaisseur** [comment]
Afaik SSL connections are transparent, i.e. you don't have to specify anything additionally. It just work's. Is there any specific problem you are experiencing?

**Comment by johnwmail** [comment]
umm… i still can use tcpdump to capture .
ex: I can see select …

**Comment by PanCakeConnaisseur** [comment]
Indeed, seems like additional settings are required. Since I neither use MySQL, nor SSL, I can't help you with that unfortunately.

**Comment by johnwmail** [comment]
Ok, thank you anyway.
