### ISSUE TITLE
SQL query doesn't seem to be executed

### ISSUE THREAD

**Issue by beerlao** [PanCakeConnaisseur/user_backend_sql_raw#14]
Hi,

I'm using NC 15.0.7 with v 1.0.6 of your plugin.
PHP: 7.2
MariaDB: 10.1.29 on Ubuntu

The 'set_password_hash_for_user' query doesn't work, while all other queries (including 'get_password_hash_for_user') are working well. I don't get any error message, the password hash isn't just going to be updated in the database. I enabled the query log on MariaDB and the SQL statement is correct. When I copy it from the log and execute in manually, it works. The statement:

'set_password_hash_for_user' => 'UPDATE accounts SET password = CONCAT(\\'{SHA512-CRYPT}\\',:new_password_hash) WHERE username = SUBSTRING_INDEX(:username, \\'@\\', 1) AND domain = SUBSTRING_INDEX(:username, \\'@\\', -1)'

(I have double backslashes included only here as they are being hidden otherwise)

Other queries:

      'get_password_hash_for_user' => 'SELECT SUBSTRING_INDEX(password, \'}\', -1) FROM users_fqda WHERE fqda = :username',
      'user_exists' => 'SELECT EXISTS(SELECT 1 FROM users_fqda WHERE fqda = :username)',
      'get_users' => 'SELECT fqda FROM users_fqda WHERE (fqda LIKE :search) OR (display_name LIKE :search)',

Any hints?

**Comment by jdsn** [comment]
@beerlao 
For `get_password_hash_for_user` you do a `SELECT ... FROM users_fqda ...`.
Why does the `set_password_hash_for_user` try to operate on a different table `UPDATE accounts ...` ?
This could be the issue. Please check that.

**Comment by beerlao** [comment]
@jdsn 
Thanks for your comments.

> For `get_password_hash_for_user` you do a `SELECT ... FROM users_fqda ...`.
> Why does the `set_password_hash_for_user` try to operate on a different table `UPDATE accounts ...` ?
> This could be the issue. Please check that.

users_fqda is just a view (i.e. a virtual table), that combines two tables (users and domains). accounts is the physical table that holds the crypted password - so that shouldn't be the problem.

**Comment by jdsn** [comment]
@beerlao Then I recommend to get to the issue slowly.
1. change the SQL statement to something totally different and static to verify if it gets executed at all:
```
# create a table `test_table` with just one string called eg. `debug`
# and only insert a new entry into the table for `set_password_hash_for_user
set_password_hash_for_user = "insert into test_table (debug) values( NOW() );"
```
2. change the statement to be more and more dynamic: include the values one after the other.
3. Once your statement resembles the original one you can switch to the real table.

**Comment by PanCakeConnaisseur** [comment]
> I enabled the query log on MariaDB and the SQL statement is correct.

Are you saying that the query was passed properly to MariaDB? If yes, then it's probably not the app.

**Comment by beerlao** [comment]
> > @beerlao
> 
> > I enabled the query log on MariaDB and the SQL statement is correct.
> 
> Are you saying that the query was passed properly to MariaDB? If yes, then it's probably not the app.

Yes, it's correctly passed to MariaDB, so it's not the app. I just doesn't work - if I copy the statement from the log and paste it into a SQL shell, it does what it has to do. Maybe it's related to the fact that my Nextcloud SQL user is different from the SQL user that has access to the user tables. But the log also shows that the app connects with the right SQL user.

So, thank you both for your support, maybe I have to ask some MariaDB Gurus for help ;-)

**Comment by beerlao** [comment]
OK, finally got it. Due to the default config of MariaDB unde Ubuntu, I have 2 SQL users (one for external access and one for localhost). The localhost one lacked the suitable priviledges. Adding the update priviledge solved my problem. So sorry for wasting your time, apologies!

**Comment by PanCakeConnaisseur** [comment]
I am glad you could resolve the problem.
