### ISSUE TITLE
Nextcloud 16 Compatibility

### ISSUE THREAD

**Issue by ChiefPete** [PanCakeConnaisseur/user_backend_sql_raw#15]
Could the app be updated to be compatible with Nextcloud 16

Thanks

**Comment by jdsn** [comment]
:+1: please provide an update for nextcloud 16

**Comment by ChiefPete** [comment]
@jdsn I see that you forked and updated the project. Does your updated app work without errors on NC16?

Thanks.

ChiefPete

**Comment by jdsn** [comment]
@ChiefPete I forked to create the PR #16.
And as I wrote in the PR, yes, the app works fine for me, without any (more) errors.

The only issue I have (and already had before) is, that I can not create a share to a circle, but that is be a general issue and not related to the update to nextcloud 16.

**Comment by PanCakeConnaisseur** [comment]
Fixed by df72d5a0188ecc8e893deffb730bac469b3f39a3
