### ISSUE TITLE
Sharing file error - SQLSTATE[HY093]: Invalid parameter number: :username

### ISSUE THREAD

**Issue by paulieas** [PanCakeConnaisseur/user_backend_sql_raw#17]
Nextcloud v16.01
User Backend Using Raw SQL v1.0.8

I have a PostgreSQL backend. I can authenticate and log into Nextcloud successfully. But when I try to share files with other users, an error is thrown. There's a banner message that pops up for about 5 seconds: "An error occurred ("Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. "). Please try again". Here is the log entry (anonymized).

`{"reqId":"alphanum", "level":3, "time":"2019-07-20T21:11:49+00:00", "remoteAddr":"ipaddress", "user":"user@domain.com", "app":"no app in context", "method":"GET", "url":"/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=c&lookup=false&perPage=200&itemType=file", "message":{"Exception":"PDOException", "Message":"SQLSTATE[HY093]: Invalid parameter number: :username", "Code":"HY093", "Trace":[{"file":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php", "line":136, "function":"execute", "class":"PDOStatement", "type":"->", "args":[{"username":"user@domain.com"}]}, {"file":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php", "line":145, "function":"getDisplayName", "class":"OCA\\UserBackendSqlRaw\\UserBackend", "type":"->", "args":["user@domain.com"]}, {"file":"/usr/share/nextcloud/lib/private/User/Manager.php", "line":257, "function":"getDisplayNames", "class":"OCA\\UserBackendSqlRaw\\UserBackend", "type":"->", "args":["c",200,0]}, {"file":"/usr/share/nextcloud/lib/private/Collaboration/Collaborators/UserPlugin.php", "line":79, "function":"searchDisplayName", "class":"OC\\User\\Manager", "type":"->", "args":["c",200,0]}, {"file":"/usr/share/nextcloud/lib/private/Collaboration/Collaborators/Search.php", "line":65, "function":"search", "class":"OC\\Collaboration\\Collaborators\\UserPlugin", "type":"->", "args":["c",200,0, {"__class__":"OC\\Collaboration\\Collaborators\\SearchResult"}]}, {"file":"/usr/share/nextcloud/apps/files_sharing/lib/Controller/ShareesAPIController.php", "line":209, "function":"search", "class":"OC\\Collaboration\\Collaborators\\Search", "type":"->", "args":["c",[0,1,6,4],false,200,0]}, {"file":"/usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line":166, "function":"search", "class":"OCA\\Files_Sharing\\Controller\\ShareesAPIController", "type":"->", "args":["c", "file",1,200,null,false]}, {"file":"/usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php", "line":99, "function":"executeController", "class":"OC\\AppFramework\\Http\\Dispatcher", "type":"->", "args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]}, {"file":"/usr/share/nextcloud/lib/private/AppFramework/App.php", "line":126, "function":"dispatch", "class":"OC\\AppFramework\\Http\\Dispatcher", "type":"->", "args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]}, {"file":"/usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php", "line":47, "function":"main", "class":"OC\\AppFramework\\App", "type":"::", "args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController", "search", {"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"}, {"_route":"ocs.files_sharing.ShareesAPI.search"}]}, {"function":"__invoke", "class":"OC\\AppFramework\\Routing\\RouteActionHandler", "type":"->", "args":[{"_route":"ocs.files_sharing.ShareesAPI.search"}]}, {"file":"/usr/share/nextcloud/lib/private/Route/Router.php", "line":297, "function":"call_user_func", "args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"}, {"_route":"ocs.files_sharing.ShareesAPI.search"}]}, {"file":"/usr/share/nextcloud/ocs/v1.php", "line":82, "function":"match", "class":"OC\\Route\\Router", "type":"->", "args":["/ocsapp/apps/files_sharing/api/v1/sharees"]}],"File":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php", "Line":136,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36", "version":"16.0.1.1", "id":"alphanum"}`

**Comment by paulieas** [comment]
Nextcloud v16.01
User Backend Using Raw SQL v1.0.8

I have a PostgreSQL backend. I can authenticate and log in successfully. But when I try to share files with other users, an error is thrown.  There's a banner message that pops up for about 5 seconds: "An error occurred ("Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. "). Please try again". Here is the log entry (anonymized).

`{"reqId":"alphanum",
"level":3,
"time":"2019-07-20T21:11:49+00:00",
"remoteAddr":"ipaddress",
"user":"fileOwner@domain.com",
"app":"no app in context",
"method":"GET",
"url":"/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=c&lookup=false&perPage=200&itemType=file",
"message":{"Exception":"PDOException",
"Message":"SQLSTATE[HY093]: Invalid parameter number: :username",
"Code":"HY093",
"Trace":[{"file":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php",
"line":136,
"function":"execute",
"class":"PDOStatement",
"type":"->",
"args":[{"username":"fileOwner@domain.com"}]},
{"file":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php",
"line":145,
"function":"getDisplayName",
"class":"OCA\\UserBackendSqlRaw\\UserBackend",
"type":"->",
"args":["fileOwner@domain.com"]},
{"file":"/usr/share/nextcloud/lib/private/User/Manager.php",
"line":257,
"function":"getDisplayNames",
"class":"OCA\\UserBackendSqlRaw\\UserBackend",
"type":"->",
"args":["c",200,0]},
{"file":"/usr/share/nextcloud/lib/private/Collaboration/Collaborators/UserPlugin.php",
"line":79,
"function":"searchDisplayName",
"class":"OC\\User\\Manager",
"type":"->",
"args":["c",200,0]},
{"file":"/usr/share/nextcloud/lib/private/Collaboration/Collaborators/Search.php",
"line":65,
"function":"search",
"class":"OC\\Collaboration\\Collaborators\\UserPlugin",
"type":"->",
"args":["c",200,0,
{"__class__":"OC\\Collaboration\\Collaborators\\SearchResult"}]},
{"file":"/usr/share/nextcloud/apps/files_sharing/lib/Controller/ShareesAPIController.php",
"line":209,
"function":"search",
"class":"OC\\Collaboration\\Collaborators\\Search",
"type":"->",
"args":["c",[0,1,6,4],false,200,0]},
{"file":"/usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
"line":166,
"function":"search",
"class":"OCA\\Files_Sharing\\Controller\\ShareesAPIController",
"type":"->",
"args":["c",
"file",1,200,null,false]},
{"file":"/usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
"line":99,
"function":"executeController",
"class":"OC\\AppFramework\\Http\\Dispatcher",
"type":"->",
"args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},
{"file":"/usr/share/nextcloud/lib/private/AppFramework/App.php",
"line":126,
"function":"dispatch",
"class":"OC\\AppFramework\\Http\\Dispatcher",
"type":"->",
"args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},
{"file":"/usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
"line":47,
"function":"main",
"class":"OC\\AppFramework\\App",
"type":"::",
"args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController",
"search",
{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},
{"_route":"ocs.files_sharing.ShareesAPI.search"}]},
{"function":"__invoke",
"class":"OC\\AppFramework\\Routing\\RouteActionHandler",
"type":"->",
"args":[{"_route":"ocs.files_sharing.ShareesAPI.search"}]},
{"file":"/usr/share/nextcloud/lib/private/Route/Router.php",
"line":297,
"function":"call_user_func",
"args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},
{"_route":"ocs.files_sharing.ShareesAPI.search"}]},
{"file":"/usr/share/nextcloud/ocs/v1.php",
"line":82,
"function":"match",
"class":"OC\\Route\\Router",
"type":"->",
"args":["/ocsapp/apps/files_sharing/api/v1/sharees"]}],"File":"/usr/share/nextcloud/apps/user_backend_sql_raw/lib/UserBackend.php",
"Line":136,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
"version":"16.0.1.1",
"id":"alphanum"}`

**Comment by PanCakeConnaisseur** [comment]
Can you please post the queries you are using?

**Comment by PanCakeConnaisseur** [comment]
Closed due to inactivity.
