### ISSUE TITLE
allow username mapping

### ISSUE THREAD

**Issue by pille** [PanCakeConnaisseur/user_backend_sql_raw#19]
please add a query for getting the "real" username from DB, like `get_display_name` does for the full name.
my usecase: my usernames in DB are full email addresses. i'd like to use them without the domain-part in nextcloud.

**Comment by PanCakeConnaisseur** [comment]
How do you want to create new users? If they provide *user* and you need to write *user@domain.tld* to the DB, how will you know what *domain* is? You might be able to use `split_part()` like in the example.

**Comment by pille** [comment]
i create users with an external system, that provides them as DB entries.
the domain part could be a config option. i know this limits users to one domain, but that's the usecase.

**Comment by PanCakeConnaisseur** [comment]
I still don't understand the issue. Do you need help with an SQL query that you would use in one of the entries in the actual `entries` key?

**Comment by pille** [comment]
in your config you have an array of queries. i asked you to add a query which will provide the username.
when a user logs in as "username@example.com", the query may result in "username". this result should be used as the nextcloud user ID. e.g. file-storage path would be `data/username`

**Comment by PanCakeConnaisseur** [comment]
Can't the user just login as `username` and your custom SQL query adds `@example.com` and `SELECT`s from the db?

**Comment by PanCakeConnaisseur** [comment]
So how do you deal the users `admin` and `admin@example.com` then? Wouldn't they be the same user in the Nextcloud context?

[What problem are you trying to solve?](https://en.wikipedia.org/wiki/XY_problem)

**Comment by pille** [comment]
they would, but system users are ruled out by design for domains.
