### ISSUE TITLE
Support for Nextcloud 17

### ISSUE THREAD

**Issue by palmtown** [PanCakeConnaisseur/user_backend_sql_raw#21]
Hello,

Can you enable support for Nextcloud 17?

**Comment by dominiquefournier** [comment]
It work on Nextcloud 17. You just need to update the "appinfo/info.xml" file with 
<nextcloud min-version="13" max-version="17"/>

**Comment by PanCakeConnaisseur** [comment]
I am working on it. Need to run tests first.

**Comment by PanCakeConnaisseur** [comment]
I can not upload a new release at the moment since the Nextcloud apps service seems to be down. You can manually add the app to your installation from here: https://github.com/PanCakeConnaisseur/user_backend_sql_raw/releases/download/v1.0.9/user_backend_sql_raw.tar.gz

**Comment by PanCakeConnaisseur** [comment]
The service is running again, I just uploaded the new release.
