### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by aszlig** [PanCakeConnaisseur/user_backend_sql_raw#24]
Users using the Nextcloud app updater will only see the changes whenever a [`CHANGELOG.md`](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog) is present, otherwise they'd need to figure out the homepage/repository to look up what they've just updated.

So it would be nice if you could add a changelog. Thanks.

**Comment by PanCakeConnaisseur** [comment]
Thank you for the hint. I will implement this soon.

**Comment by PanCakeConnaisseur** [comment]
I forgot about this while releasing 1.0.10 but am implementing it now.

**Comment by PanCakeConnaisseur** [comment]
Done https://github.com/PanCakeConnaisseur/user_backend_sql_raw/commit/1d697ee59b0831c5a63d1e7a1985515be5ef0ffd
