### ISSUE TITLE
Can I connect to DB using a unix: socket?

### ISSUE THREAD

**Issue by oucil** [PanCakeConnaisseur/user_backend_sql_raw#27]
Is it possible to connect to the DB via a unix: socket rather than via TCP?  If so, how?

Thanks,
Kevin.

**Comment by oucil** [comment]
Nevermind, I inspected the code and see that it's not able.  I've forked and am preparing a pull request.

**Comment by PanCakeConnaisseur** [comment]
It works with PostgreSQL out-of-the-box. Regarding MySQL, see this comment on your [PR](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/pull/29#issuecomment-2083832651).
