### ISSUE TITLE
Add the allowed db_type

### ISSUE THREAD

**Issue by dominiquefournier** [PanCakeConnaisseur/user_backend_sql_raw#3]
Bonjour 
It may be good to provide the allowed "db_type" config values : I have test "mysql" (and have a big stack exception in logs without readable error), instead of "mariadb".
It may be interesting to have a message "Invalid db-type provided" in the exception instead of "Could not resolve db! Class db does not exist"

Thanks !
Dom

**Comment by PanCakeConnaisseur** [comment]
I opened an issue with Nextcloud server: https://github.com/nextcloud/server/issues/10263

**Comment by PanCakeConnaisseur** [comment]
I added a hint in the README.md as requested.
