### ISSUE TITLE
Incorrect user count

### ISSUE THREAD

**Issue by tripougnif** [PanCakeConnaisseur/user_backend_sql_raw#32]
I have a small 15 users instance. occ user:report returns:
```
+------------------+----+
| User Report      |    |
+------------------+----+
| Database         | 0  |
| SQL raw          | 30 |
|                  |    |
| total users      | 30 |
|                  |    |
| user directories | 2  |
| disabled users   | 0  |
+------------------+----+
```
The user management interface returns the same count. If I comment out the count_users query from config.php, I get:
```
+------------------+---+
| User Report      |   |
+------------------+---+
| Database         | 0 |
|                  |   |
| total users      | 0 |
|                  |   |
| user directories | 2 |
| disabled users   | 0 |
+------------------+---+
```
So it does look like your countUsers method is called twice.

The user management interface does show my 15 users but it also shows "No users" at the bottom of the page, whether the count_users query is enabled or not. See the attached screenshot.

![image](https://user-images.githubusercontent.com/498487/111909414-92746980-8a33-11eb-935b-5d7355e953b7.png)

I think this behavior started after an update (I'm currently on 20.0.8) but I'm not sure which one.

I don't see anything useful in the log.

**Comment by gpgmailencrypt** [comment]
Same here. I am just not quite sure if this is a problem of this backend or of nextcloud itself

**Comment by PanCakeConnaisseur** [comment]
1. I checked my instances and the reported user count is correct there.
2. What SQL query are you using for `count_users`? Did you run in manually in the DB and does it return 15? MySQL or PostgreSQL?
3. I also have this "No users here" message. Never noticed it. This seems to be a bug in Nextcloud. If it lists users, it should know that there are >0.

**Comment by PanCakeConnaisseur** [comment]
Regarding the "No users here" message: https://github.com/nextcloud/server/issues/27047

**Comment by tripougnif** [comment]
I did run the `count_users` sql query manually against my Postgresql DB and was reporting the right user count. Since the last update, the user count is now correct. I still see the "No users here" message but you took care of reporting this to the Nextcloud folk. Thanks!

Out of curiosity, was something changed to address the issue or did it magically disappear?

**Comment by PanCakeConnaisseur** [comment]
AFAICS/R nothing has changed in the affected code. One of the things that did change is the bootstrapping code. The user backend is registered differently now and maybe that does not cause a bug that is/was hidden somewhere in Nextcloud. I doubt it was the user backend itself, since the test should have caught any query being run twice.

I am closing this, since the issue fortunately seems to be resolved now.
