### ISSUE TITLE
Check Nextcloud 21 compatibility

### ISSUE THREAD

**Issue by kescherCode** [PanCakeConnaisseur/user_backend_sql_raw#33]
Currently, this app is a blocker for an upgrade to Nextcloud 21. Therefore, if the app works with Nextcloud 21, the `max-version` needs to be increased and an update needs to be pushed.

**Comment by pvalsecc** [comment]
I've changed appinfo/info.xml to increase max-version to 21 and the app works like a charm. But I'm using only the following queries:
* get_password_hash_for_user
* user_exists
* get_users
* get_display_name
* count_users

**Comment by Tachi107** [comment]
Fixed by 8edc6b848a7d18eb88767f2cd935e2d310a2c179
