### ISSUE TITLE
Salt size too small in hashWithOldMethod

### ISSUE THREAD

**Issue by lebuzzer** [PanCakeConnaisseur/user_backend_sql_raw#37]
Hello, I'm using dovecot to retrieve my mails on a Nextcloud system. When using SHA512 passwords, auth fail due to salt length.
When changing salt to "base64_encode(random_bytes(16))", auth with dovecot is working.
I do not know if such modification is ok for other algorithms (sha256 & md5)

**Comment by PanCakeConnaisseur** [comment]
Can you provide more details please. What exactly is failing when? Dovecot can not handle the hashes created by this app when using SHA-512?

**Comment by lebuzzer** [comment]
Dovecot cannot handle password when using "$salt = base64_encode(random_bytes(8));". When using "$salt = base64_encode(random_bytes(12));" everything is working like a charm. I currently use sha512 and confirm that changing salt length is ok with dovecot. I do not know, and did not test, with sha256 and md5.

**Comment by PanCakeConnaisseur** [comment]
What error is Dovecot giving you specifically? The increased length of the salt does not change the syntax of `crypt()`s output.

**Comment by lebuzzer** [comment]
Dovecot error :
imap-login: Disconnected (auth failed, 1 attempts in 2 secs)

password with salt of 8 (CZ75mOjJc3Q=): $6$CZ75mOjJc3Q=$7LDPEGOsuEIQPGlsWJO51ag9sJQUUm0x1i56qEGptuLIVZO3wXIgqCq6mJpyztqRtLXLuTfSLYrlinio0QINZ1
same password with salt of 12 (WZFsJer26/vzrOCm) :
$6$WZFsJer26/vzrOCm$nCb4OIcwwKs0zhBkjR2euYzcRQperEIZSFiHqPQ2vsH5mAZD9GfEUbr/gNgv6YJ2ZNPuWvDE6EecYxJ6ogAo21

no error with salt of 12.

**Comment by lebuzzer** [comment]
Please consider that I do not say that your implementation of SHA512-crypt is false, but it is not compatible with dovecot implementation, which is (I think) one the most used imap server.

**Comment by PanCakeConnaisseur** [comment]
The output of the `crypt()` function looks fine. The salt length is variable and can be shorter than 16 bytes (128 bits). Are you sure you used the same password to create the hashes? Also, make sure that the string is stored to the DB in its entirety, i.e nothing is cut off.

**Comment by lebuzzer** [comment]
There is no issue with nextcloud using password with small salt. Only dovecot 2.3.7.2 with SHA512-CRYPT has issue with salt smaller than 12 characters in the code. there is no issue with database as row is 128 characters long for password storage.
and yes same passord was used for the example : AzErTyUiOp . Just the length of salt was changed. If you are using dovecot and SHA512-Crypt, you can test with a new account as the existing accounts are not amend as long as nobody change password during test.

**Comment by PanCakeConnaisseur** [comment]
Sorry, this issue got lost in time. I will close now, assuming that it is resolved or stale, but feel free to reopen this or create a new one.
