### ISSUE TITLE
Compatibility with nc 23

### ISSUE THREAD

**Issue by MarkTr** [PanCakeConnaisseur/user_backend_sql_raw#38]
Last release is incompatible with nextcloud 23.

**Comment by 1358** [comment]
however it works fine after forcefully re-enabling it via `./occ app:enable user_backend_sql_raw --force`

**Comment by PanCakeConnaisseur** [comment]
Solved with https://github.com/PanCakeConnaisseur/user_backend_sql_raw/commit/0b5b6b1907d3865dc08bcf20d85d8f16299767d4
