### ISSUE TITLE
Compatibility with nc 23

### ISSUE THREAD

**Issue by exmerc** [PanCakeConnaisseur/user_backend_sql_raw#39]
Hi bro

Do you have in your plans to make the module compatible with NC 23?

**Comment by 1358** [comment]
it seems as if it is compatible as forcefully re-enabling it via `./occ app:enable user_backend_sql_raw --force` works fine now for a couple of weeks without any issues

**Comment by scchearn** [comment]
Is this still the case? Forcefully enabling it? What needs to change for it to be seen as compatible?

**Comment by 1358** [comment]
It is still working "fine" here with NC23.0.3

However I did not dig into details

**Comment by gpgmailencrypt** [comment]
Technically it would be quite easy. The "max-version" entry in this file has to be updated
[https://github.com/PanCakeConnaisseur/user_backend_sql_raw/blob/7f23823d850578761082d3666f88b5793c7821f6/appinfo/info.xml#L34](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/blob/7f23823d850578761082d3666f88b5793c7821f6/appinfo/info.xml#L34)
But this can only be done by the code owner

**Comment by PanCakeConnaisseur** [comment]
Duplicate of #38

**Comment by PanCakeConnaisseur** [comment]
Since I have been applying all NC architecture changes immediately in the app, it will likely always work for several subsequent versions when you force its usage as someone suggested above.
