### ISSUE TITLE
Add support for hash algorythm 'Joomla MD5 Encryption' possible?

### ISSUE THREAD

**Issue by Beamou** [PanCakeConnaisseur/user_backend_sql_raw#44]
Hello, we (a german private society) want to use your app in NC 24 but we have a user db from an Joomla installation.
Afaik Joomla has an specific hash algorithm (Joomla MD5 Encryption) and it seems, your app don't support this algorythm.
Is it possible to implement this support?
Thanks in advance!

**Comment by PanCakeConnaisseur** [comment]
Is this still open? I am closing for assumed staleness but feel free to reopen or comment.

I hope Joomla has arrived in the 21st century and now offers a proper hash algorithm such as bcrypt at least.
