### ISSUE TITLE
Request: Password for admin user

### ISSUE THREAD

**Issue by Mitschmaster** [PanCakeConnaisseur/user_backend_sql_raw#47]
The password for the admin user seems to be stored in the nextcloud database and not in the apps database.
I tried to figure out how to update both locations, but failed.
Does somebody have an idea on how that may work?

**Comment by PanCakeConnaisseur** [comment]
I can see how what you want would fit into this app at first glance. What this app does though, is implementing a user management interface which is defined in Nextcloud and this interface does not include methods for reading/writing the admin password AFAIK. Therefore, this app has no way of intercepting this to read/write it from a SQL database instead.

The only solution I can think of, is to write a trigger that would change the admin password of the Nextcloud user when another user in your other db is changed. But that is pretty hacky.
