### ISSUE TITLE
Can't install in Nextcloud 13 docker

### ISSUE THREAD

**Issue by gcleaves** [PanCakeConnaisseur/user_backend_sql_raw#6]
Hi. I'd really like to use this app to authenticate against another DB since all my users already exist there. But when installing via the front end, I get an error immediately and Nextcloud stops working. I am using the docker fpm image of Nextcloud 13.

The front end shows me this: `Error: Could not disable broken app` and the log gives the message below:

```{"reqId":"bQ3KPsH1dg1bIRcEPFUN","level":3,"time":"2018-07-23T17:37:00+00:00","remoteAddr":"172.27.0.1","user":"admin","app":"index","method":"GET","url":"\/apps\/files","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve config! Class config does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('config')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('config')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(74): OC\\\\ServerContainer->query('config')\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(97): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\UserBackend...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\UserBackend...')\\n#6 \\\/var\\\/www\\\/html\\\/custom_apps\\\/user_backend_sql_raw\\\/lib\\\/AppInfo\\\/Application.php(56): OC\\\\ServerContainer->query('OCA\\\\\\\\UserBackend...')\\n#7 \\\/var\\\/www\\\/html\\\/custom_apps\\\/user_backend_sql_raw\\\/appinfo\\\/app.php(21): OCA\\\\UserBackendSqlRaw\\\\AppInfo\\\\Application->__construct()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(245): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(154): OC_App::requireAppFile('user_backend_sq...')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('user_backend_sq...')\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/user.php(131): OC_App::loadApps(Array)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(729): OC_User::setupBackends()\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1081): OC::init()\\n#14 \\\/var\\\/www\\\/html\\\/index.php(40): require_once('\\\/var\\\/www\\\/html\\\/l...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}```

Any ideas of what it might be?

**Comment by gcleaves** [comment]
Editing the config.php seems to have resolved my issue.

**Comment by PanCakeConnaisseur** [comment]
@gcleaves Glad it worked out!
