### ISSUE TITLE
Add more documentation examples for configuring the SQL querys

### ISSUE THREAD

**Issue by jamasi** [PanCakeConnaisseur/user_backend_sql_raw#8]
I'd really like to see an example for configuring the authentication against a redmine DB or some other commonly used tools.

**Comment by PanCakeConnaisseur** [comment]
I am not familiar with redmine DB, but feel to provide some examples. I will close this, since this is not an issue of the app itself. If someone provides examples, I can enable the "wiki" feature so that they can be posted there.
