### ISSUE TITLE
My users don't have an email

### ISSUE THREAD

**Issue by sexygeoff** [PanCakeConnaisseur/user_backend_sql_raw#9]
Hi, my external DB user's don't have email addresses. How can I fix this?  Here is relevant portion of config file:

```
    array (
      'get_password_hash_for_user' => 'SELECT password FROM table WHERE email = :username',
      'user_exists' => 'SELECT EXISTS(SELECT 1 FROM table WHERE email = :username)',
      'get_users' => 'SELECT email FROM table WHERE ((email LIKE :search) OR (company_name LIKE :search)) and (trial_expires_at >= now() or trial_expires_at is nul
l)',
      'get_display_name' => 'SELECT company_name FROM table WHERE email = :username',
      'count_users' => 'SELECT COUNT(*) FROM table WHERE (trial_expires_at >= now() or trial_expires_at is null)',
    ),
```

Thanks!

Any ideas, @PanCakeConnaisseur ?

**Comment by sexygeoff** [comment]
Nothing?

**Comment by PanCakeConnaisseur** [comment]
Sorry, I am extremely busy at the moment. I wont't be able to take care of issues until next week (or the one after). But rest assured, that it did not go unnoticed.

**Comment by PanCakeConnaisseur** [comment]
@sexygeoff 
What are you trying to achieve? If you don't have e-mail addresses then don't query them. It seems that this is not an issue in user_backend_sql_raw. Feel free to reopen if you feel this is an issue of the app.
